apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrelik-worker-extraction
  namespace: openrelik
  labels:
    worker: extraction
spec:
  replicas: {{ .Values.openrelik.worker.extraction.replicas }}
  selector:
    matchLabels:
      worker: extraction
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        worker: extraction
    spec:
      initContainers:
        - name: create-dirs
          image: busybox:1.37
          command: ['sh', '-c', "mkdir -p /usr/share/openrelik/data/artifacts; mkdir -p /usr/share/openrelik/config"]
          volumeMounts:
          - name: vol-data
            mountPath: /usr/share/openrelik
      containers:
        - name: openrelik-worker-extraction
          image: {{ .Values.openrelik.worker.extraction.image }}
          {{- if .Values.global.useResourceRequests }}
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
          {{- end }}
          args:
            - celery
            - --app=src.app
            - worker
            - --task-events
            - --concurrency=2
            - --loglevel=INFO
            - -Q
            - openrelik-worker-extraction
          env:
            - name: OPENRELIK_PYDEBUG
              value: "0"
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
          volumeMounts:
          - name: vol-data
            mountPath: /usr/share/openrelik
      restartPolicy: Always
      volumes:
        {{- if .Values.global.localData }}
        - name: vol-data
          persistentVolumeClaim:
            claimName: pvc-local
        {{- end }}
        {{- if .Values.filestore.managed }}
        - name: vol-data
          persistentVolumeClaim:
            claimName: pvc-filestore
        {{- end }}
