{{- if .Values.postgres.selfManaged }}
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  namespace: openrelik
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: openrelik-postgres
{{- end }}
