apiVersion: v1
kind: Service
metadata:
  name: svc-ui
  namespace: openrelik
spec:
  ports:
    - name: "ui"
      port: {{ .Values.openrelik.ui.port }}
      targetPort: {{ .Values.openrelik.ui.port }}
  selector:
    app: ui
