{{- if .Values.postgres.managedSecret }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sec-openrelik-db
  namespace: openrelik
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/openrelik/versions/{{ .Values.postgres.managedSecretVersion }}"
        path: "password.txt"
{{- end }}
