{{- if .Values.gateway.managed }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hc-server
  namespace: openrelik
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: TCP
      httpHealthCheck:
        port: {{ .Values.openrelik.server.port }}
  targetRef:
    group: ""
    kind: Service
    name: svc-server
{{- end }} 
